"""Generate cpp/src/strip_grid_table.inc: the strip grid (u, v) from endfield/preprocess.strip_roi_uv().

The grid is the only transcendental part of the preprocess (float32 sin / cos). Different libm
implementations (MSVC, bionic, numpy, torch) disagree in the last ulp for ~5% of the 15120 points,
which then shows up as 1 LSB strip differences. Baking the definition's own float32 values (bit
exact, the same values the exported graph stores as constants) removes that source of drift and
makes the C++ result identical across platforms.

Run from the repo root:  uv run python cpp/tools/gen_strip_grid.py [--check]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

from endfield import preprocess as pp  # noqa: E402

OUT = REPO / "cpp" / "src" / "strip_grid_table.inc"


def render() -> str:
    uv = pp.strip_roi_uv().numpy().astype(np.float32)
    assert uv.shape == (pp.IMG_H, pp.IMG_W, 2)
    lines = [
        "// Generated by cpp/tools/gen_strip_grid.py from endfield/preprocess.strip_roi_uv(). Do not edit.",
        f"// definition_hash {pp.definition_hash()}",
        f"// shape [{pp.IMG_H}][{pp.IMG_W}] float32 bit patterns, ROI pixel-center coordinates",
        f'#define CAMORI_STRIP_GRID_DEFINITION_HASH "{pp.definition_hash()}"',
    ]
    for axis, name in ((0, "kStripGridU"), (1, "kStripGridV")):
        bits = uv[..., axis].view(np.uint32).reshape(-1)
        lines.append(f"inline constexpr uint32_t {name}[{bits.size}] = {{")
        for i in range(0, bits.size, 12):
            lines.append("    " + ", ".join(f"0x{b:08x}u" for b in bits[i : i + 12]) + ",")
        lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail if the checked-in table is stale")
    a = ap.parse_args()
    text = render()
    if a.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT} is stale; rerun cpp/tools/gen_strip_grid.py")
            return 1
        print(f"{OUT} up to date")
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
