"""Generate cpp/src/CameraOrientationAzimuthTable.inc: float32 sin / cos of the strip azimuths.

sin / cos are the only transcendental part of the preprocess. Different libm implementations
(MSVC, bionic, numpy, torch) disagree in the last ulp for a few percent of the 360 azimuths,
which then shows up as 1 LSB strip differences. The C++ port takes the definition's own float32
values from this table and computes radius and u / v itself in float32; before writing, the same
C++ arithmetic is replayed here in numpy and must reproduce strip_roi_uv() bit for bit.

Run from the repo root:  uv run python cpp/tools/gen_azimuth_table.py [--check]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import torch

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

from endfield import preprocess as pp  # noqa: E402

OUT = REPO / "cpp" / "src" / "CameraOrientationAzimuthTable.inc"
PER_LINE = 8


def azimuth_sin_cos() -> tuple[np.ndarray, np.ndarray]:
    theta = torch.deg2rad(torch.arange(pp.IMG_W, dtype=torch.float32))
    return torch.sin(theta).numpy(), torch.cos(theta).numpy()


def check_grid(sin: np.ndarray, cos: np.ndarray) -> None:
    """Replay StripGrid() of CameraOrientationPreprocess.cpp in float32 against strip_roi_uv()."""
    f32 = np.float32
    step = (f32(pp.OUTER_R) - f32(pp.INNER_R)) / f32(pp.IMG_H)
    radius = f32(pp.INNER_R) + step * (np.arange(pp.IMG_H, dtype=f32) + f32(0.5))
    u = f32(pp.ROI_POLE[0]) + radius[:, None] * sin[None, :]
    v = f32(pp.ROI_POLE[1]) - radius[:, None] * cos[None, :]
    uv = pp.strip_roi_uv().numpy()
    for name, ours, theirs in (("u", u, uv[..., 0]), ("v", v, uv[..., 1])):
        if ours.dtype != f32 or not np.array_equal(ours.view(np.uint32), theirs.view(np.uint32)):
            raise SystemExit(
                f"C++ strip grid {name} no longer reproduces strip_roi_uv(); "
                "update StripGrid() in CameraOrientationPreprocess.cpp and this check"
            )


def render() -> str:
    sin, cos = azimuth_sin_cos()
    check_grid(sin, cos)
    lines = [
        "// Generated by cpp/tools/gen_azimuth_table.py from endfield/preprocess.py. Do not edit.",
        "// torch.sin / torch.cos(torch.deg2rad(torch.arange(360, dtype=torch.float32))) "
        "as float32 bit patterns.",
        "// Included inside an anonymous namespace by CameraOrientationPreprocess.cpp.",
        "",
        f'constexpr std::string_view kAzimuthTableDefinitionHash = "{pp.definition_hash()}";',
        "",
    ]
    for name, values in (("kAzimuthSinBits", sin), ("kAzimuthCosBits", cos)):
        bits = values.astype(np.float32).view(np.uint32)
        lines.append(f"constexpr std::array<uint32_t, kOrientationStripWidth> {name} = {{")
        for i in range(0, bits.size, PER_LINE):
            lines.append("    " + ", ".join(f"0x{b:08x}" for b in bits[i : i + PER_LINE]) + ",")
        lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--check", action="store_true", help="fail if the checked-in table is stale")
    a = ap.parse_args()
    text = render()
    if a.check:
        current = OUT.read_bytes().decode("utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT} is stale; rerun cpp/tools/gen_azimuth_table.py")
            return 1
        print(f"{OUT} up to date")
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
